refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
  file:
    kind: file
    path: "error.log"
    encoder:
      pattern: "{d} [{l}] {M}:{m}{n}"

root:
  level: error
  appenders:
    - file
